fail_fast: true
repos:
- repo: local
  hooks:
    - id: isort
      name: isort
      entry: poetry run isort
      language: system
      types: [file, python]
    - id: black
      name: black
      entry: poetry run black --preview --enable-unstable-feature string_processing
      language: system
      types: [file, python]
    - id: flake8
      name: flake8
      entry: poetry run flake8
      language: system
      types: [file, python]